# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joy_bidirection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15joy_bidirection.proto\"(\n\x07Message\x12\x0f\n\x07\x62uttons\x18\x01 \x03(\x05\x12\x0c\n\x04\x61xes\x18\x02 \x03(\x02\"\x1d\n\nMyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\rBidirectional\x12,\n\x11GetServerResponse\x12\x08.Message\x1a\x0b.MyResponse\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MYRESPONSE = DESCRIPTOR.message_types_by_name['MyResponse']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'joy_bidirection_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

MyResponse = _reflection.GeneratedProtocolMessageType('MyResponse', (_message.Message,), {
  'DESCRIPTOR' : _MYRESPONSE,
  '__module__' : 'joy_bidirection_pb2'
  # @@protoc_insertion_point(class_scope:MyResponse)
  })
_sym_db.RegisterMessage(MyResponse)

_BIDIRECTIONAL = DESCRIPTOR.services_by_name['Bidirectional']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=25
  _MESSAGE._serialized_end=65
  _MYRESPONSE._serialized_start=67
  _MYRESPONSE._serialized_end=96
  _BIDIRECTIONAL._serialized_start=98
  _BIDIRECTIONAL._serialized_end=159
# @@protoc_insertion_point(module_scope)
