# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import p2p_demo_app.joy_bidirection_pb2 as joy__bidirection__pb2


class BidirectionalStub(object):
    """package bidirectional;

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerResponse = channel.unary_unary(
                '/Bidirectional/GetServerResponse',
                request_serializer=joy__bidirection__pb2.Message.SerializeToString,
                response_deserializer=joy__bidirection__pb2.MyResponse.FromString,
                )


class BidirectionalServicer(object):
    """package bidirectional;

    """

    def GetServerResponse(self, request, context):
        """A Bidirectional streaming RPC.

        Accepts a stream of Message sent while a route is being traversed,
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BidirectionalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponse,
                    request_deserializer=joy__bidirection__pb2.Message.FromString,
                    response_serializer=joy__bidirection__pb2.MyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bidirectional', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bidirectional(object):
    """package bidirectional;

    """

    @staticmethod
    def GetServerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bidirectional/GetServerResponse',
            joy__bidirection__pb2.Message.SerializeToString,
            joy__bidirection__pb2.MyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
