# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0bHelloButton\x12\x11\n\temrButton\x18\x01 \x01(\x08\"\'\n\x14HelloBackpackButtons\x12\x0f\n\x07\x62uttons\x18\x01 \x03(\x08\x32\xcd\x01\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x32\n\x0fSayButtonStream\x12\x0c.HelloButton\x1a\x0b.HelloReply\"\x00(\x01\x30\x01\x12(\n\tSayButton\x12\x0c.HelloButton\x1a\x0b.HelloReply\"\x00\x12:\n\x12SayBackpackButtons\x12\x15.HelloBackpackButtons\x1a\x0b.HelloReply\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_HELLOBUTTON = DESCRIPTOR.message_types_by_name['HelloButton']
_HELLOBACKPACKBUTTONS = DESCRIPTOR.message_types_by_name['HelloBackpackButtons']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

HelloButton = _reflection.GeneratedProtocolMessageType('HelloButton', (_message.Message,), {
  'DESCRIPTOR' : _HELLOBUTTON,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:HelloButton)
  })
_sym_db.RegisterMessage(HelloButton)

HelloBackpackButtons = _reflection.GeneratedProtocolMessageType('HelloBackpackButtons', (_message.Message,), {
  'DESCRIPTOR' : _HELLOBACKPACKBUTTONS,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:HelloBackpackButtons)
  })
_sym_db.RegisterMessage(HelloBackpackButtons)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=20
  _HELLOREQUEST._serialized_end=48
  _HELLOREPLY._serialized_start=50
  _HELLOREPLY._serialized_end=79
  _HELLOBUTTON._serialized_start=81
  _HELLOBUTTON._serialized_end=113
  _HELLOBACKPACKBUTTONS._serialized_start=115
  _HELLOBACKPACKBUTTONS._serialized_end=154
  _GREETER._serialized_start=157
  _GREETER._serialized_end=362
# @@protoc_insertion_point(module_scope)
